deployment:
  tasks:
    - /bin/mkdir -p /home/lbccompa/testportal.cca.it.com/storage/framework/cache/data
    - /bin/mkdir -p /home/lbccompa/testportal.cca.it.com/storage/framework/sessions
    - /bin/mkdir -p /home/lbccompa/testportal.cca.it.com/storage/framework/views
    - /bin/mkdir -p /home/lbccompa/testportal.cca.it.com/storage/logs
    - /bin/mkdir -p /home/lbccompa/testportal.cca.it.com/bootstrap/cache
    - /usr/bin/env composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev --working-dir=/home/lbccompa/testportal.cca.it.com
    - /usr/bin/env npm --prefix /home/lbccompa/testportal.cca.it.com ci --no-audit --no-fund
    - /usr/bin/env npm --prefix /home/lbccompa/testportal.cca.it.com run build
    - /usr/bin/env php /home/lbccompa/testportal.cca.it.com/artisan optimize:clear
    - /usr/bin/env php /home/lbccompa/testportal.cca.it.com/artisan config:cache
    - /usr/bin/env php /home/lbccompa/testportal.cca.it.com/artisan view:cache
    - /bin/chmod -R 775 /home/lbccompa/testportal.cca.it.com/storage
    - /bin/chmod -R 775 /home/lbccompa/testportal.cca.it.com/bootstrap/cache
