<?php

return [
    /*
    |--------------------------------------------------------------------------
    | CCA Programs Configuration
    |--------------------------------------------------------------------------
    |
    | This file contains all available programs with their codes, names,
    | years, and durations. Add new programs here as needed.
    |
    */

    'programs' => [
        'CCA-FS25' => [
            'name' => 'Full Stack Developer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-FE25' => [
            'name' => 'Frontend Developer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-BE25' => [
            'name' => 'Backend Developer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-MA25' => [
            'name' => 'Mobile App Developer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-SE25' => [
            'name' => 'Software Engineer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-DA25' => [
            'name' => 'Data Analyst Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-DS25' => [
            'name' => 'Data Scientist Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-DE25' => [
            'name' => 'Data Engineer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-AI25' => [
            'name' => 'AI ML Engineer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-UX25' => [
            'name' => 'UI UX Designer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-GD25' => [
            'name' => 'Graphic Designer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-DM25' => [
            'name' => 'Digital Marketing Specialist Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-SEO25' => [
            'name' => 'SEO AEO Specialist Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-DO25' => [
            'name' => 'DevOps Engineer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-QA25' => [
            'name' => 'QA Engineer Manual Automation Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-PM25' => [
            'name' => 'Project Manager Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-BA25' => [
            'name' => 'Business Analyst Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
        'CCA-CS25' => [
            'name' => 'Cyber Security Engineer Career Accelerator',
            'year' => '2025',
            'duration' => '6 Months',
        ],
    ],


    /*
    |--------------------------------------------------------------------------
    | Sri Lanka Districts and Provinces
    |--------------------------------------------------------------------------
    */

    'sri_lanka_districts' => [
        'Western' => ['Colombo', 'Gampaha', 'Kalutara'],
        'Central' => ['Kandy', 'Matale', 'Nuwara Eliya'],
        'Southern' => ['Galle', 'Matara', 'Hambantota'],
        'Northern' => ['Jaffna', 'Kilinochchi', 'Mannar', 'Vavuniya', 'Mullaitivu'],
        'Eastern' => ['Batticaloa', 'Ampara', 'Trincomalee'],
        'North Western' => ['Kurunegala', 'Puttalam'],
        'North Central' => ['Anuradhapura', 'Polonnaruwa'],
        'Uva' => ['Badulla', 'Moneragala'],
        'Sabaragamuwa' => ['Ratnapura', 'Kegalle'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Countries List (All Countries)
    |--------------------------------------------------------------------------
    |
    | Sri Lanka is listed first as it's the primary country for this application.
    | Other countries follow in alphabetical order.
    |
    */

    'countries' => [
        'Sri Lanka',
        '---', // Separator
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'Brunei',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Central African Republic',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'Comoros',
        'Congo (Congo-Brazzaville)',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czech Republic',
        'Democratic Republic of the Congo',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Eswatini',
        'Ethiopia',
        'Fiji',
        'Finland',
        'France',
        'Gabon',
        'Gambia',
        'Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Grenada',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Honduras',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Micronesia',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Myanmar',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'North Korea',
        'North Macedonia',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Rwanda',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'South Korea',
        'South Sudan',
        'Spain',
        'Sudan',
        'Suriname',
        'Sweden',
        'Switzerland',
        'Syria',
        'Taiwan',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Vatican City',
        'Venezuela',
        'Vietnam',
        'Yemen',
        'Zambia',
        'Zimbabwe',
    ],
];
